replicaCount: 1

image:
  repository: 630019796862.dkr.ecr.us-east-1.amazonaws.com/retail-store-checkout
  tag: "d91aa66b93154ba5115151df0316c007ee98cb72"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

endpoints:
  orders: "http://orders:80"
  carts: "http://cart:80"

rabbitmq:
  endpoint: "rabbitmq:5672"
  user: "guest"
  password: "guest"
